services:
  wr-scraper:
    build: .
    container_name: wr-scraper
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3